Add blog Crud
SakshiUppoor/unicode-group-task pull request #8
Opened 2020-11-05 08:04 UTC by ksuvarna85

2020-11-05 14:25 UTC, SakshiUppoor requested changes

2020-11-05 14:25 UTC, SakshiUppoor commented on blogApp/views.py
> +class BlogDetail(APIView):
Detail view is missing

2020-11-06 03:49 UTC, Harshvartak commented on blogApp/models.py
> +    last_updated=models.CharField(max_length=30)
last_updated and created_on to be datefield instead of charfield

2020-11-06 03:54 UTC, Harshvartak requested changes
1. created_on,last_update to be in the form of dateField
2. blog creation has an issue with swagger docs, check the serializer and its save method, make sure it runs on swagger docs before a PR

2020-11-06 11:14 UTC, Harshvartak approved these changes

2020-11-06 11:15 UTC, SakshiUppoor approved these changes

2020-11-06 11:16 UTC, merged